name:                lev
version:             0.0.0.0
synopsis:            Toy language
description:         Blah
homepage:            http://github.com/jkarni/lev
license:             BSD3
license-file:        LICENSE
author:              Julian K. Arni
maintainer:          jkarni@gmail.com
category:            Language
copyright:           (c) Julian K. Arni
github:              jkarni/lev
tested-with:         GHC == 8.0.1

extra-source-files:
  - package.yaml

ghc-options: -Wall

dependencies:
  - base
  - bound
  - bound-gen
  - deriving-compat
  - containers
  - mtl
  - monad-gen
  - lens
  - text
  - trifecta
  - parsers
  - prettyprinter
  - prettyprinter-ansi-terminal

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - KindSignatures
  - MultiParamTypeClasses
  - OverloadedStrings
  - StandaloneDeriving
  - RankNTypes
  - ScopedTypeVariables
  - TypeFamilies
  - TypeOperators

library:
  source-dirs:      src
  other-modules:    []

tests:
  spec:
    main:            Spec.hs
    source-dirs:     test
    dependencies:
      - hspec
      - QuickCheck
      - lev

executables:
  dt:
    main:            Dt.hs
    source-dirs:     exe
    dependencies:
      - QuickCheck
      - optparse-applicative
      - lev
